name: phirse
description: Auto-reorder app for essentials via calls
version: 1.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  # your other dependencies...
